
    create table animali (
        altezza float(53) not null,
        area integer unique,
        aspettativa_vita integer not null,
        data_arrivo date not null,
        eta integer not null,
        id integer generated by default as identity,
        mangime integer unique,
        pericolosita boolean not null,
        peso float(53) not null,
        sesso varchar(20) not null,
        colore varchar(50) not null,
        dieta varchar(50) not null,
        habitat varchar(50) not null,
        provenienza varchar(50) not null,
        specie varchar(50) not null,
        primary key (id)
    );

    create table area (
        area integer,
        id integer generated by default as identity,
        turni integer,
        tipo_struttura varchar(255) not null,
        primary key (id)
    );

    create table biglietti (
        data_biglietto date not null,
        eventi integer,
        id integer generated by default as identity,
        prezzo_biglietto integer not null,
        prodotti integer unique,
        primary key (id)
    );

    create table clienti (
        id integer generated by default as identity,
        utenti integer unique,
        cognome varchar(255) not null,
        email varchar(255) not null,
        indirizzo varchar(255) not null,
        nome varchar(255) not null,
        primary key (id)
    );

    create table delfini (
        id integer not null,
        velocità_massima float(53) not null,
        comportamento_riproduttivo varchar(30) not null,
        tipo_dentatura varchar(30) not null,
        primary key (id)
    );

    create table dipendenti (
        area integer,
        id integer generated by default as identity,
        utenti integer unique,
        primary key (id)
    );

    create table eventi (
        data_evento date not null,
        id integer generated by default as identity,
        tipo_evento varchar(255) not null,
        primary key (id)
    );

    create table giornata_zoo (
        data_giornata_zoo date not null,
        eventi integer,
        giornate integer,
        id integer generated by default as identity,
        primary key (id)
    );

    create table lemuri (
        id integer not null,
        lunghezza_coda float(53) not null,
        attività_diurna varchar(30) not null,
        tipo_movimento varchar(30) not null,
        primary key (id)
    );

    create table leoni (
        id integer not null,
        lunghezza_criniera float(53) not null,
        numero_cuccioli integer not null,
        velocita_massima float(53) not null,
        primary key (id)
    );

    create table mangime (
        animali integer unique,
        id integer generated by default as identity,
        tipo_mangime varchar(255) not null,
        primary key (id)
    );

    create table messaggi_systema (
        lang varchar(4) not null,
        code varchar(50) not null,
        messaggio varchar(255),
        primary key (lang, code)
    );

    create table movimenti_mangime (
        dipendenti integer,
        id integer generated by default as identity,
        movimenti_mangime integer,
        movimento boolean not null,
        primary key (id)
    );

    create table oggetti_ordine (
        id integer generated by default as identity,
        oggetti_ordine integer,
        oggetti_ordini integer,
        ordini integer,
        prodotti integer,
        quantita integer not null,
        totale integer not null,
        primary key (id)
    );

    create table ordine (
        data_ordine date not null,
        id integer generated by default as identity,
        ordine integer,
        cognome varchar(255) not null,
        indirizzo varchar(255) not null,
        nome varchar(255) not null,
        primary key (id)
    );

    create table pesci (
        id integer not null,
        migrazione boolean not null,
        profondita_max integer not null,
        squame boolean not null,
        branchie_tipo varchar(255) not null,
        tipo_acqua varchar(255) not null,
        primary key (id)
    );

    create table pinguini (
        id integer not null,
        impermeabilita boolean not null,
        uova_media integer not null,
        velocita_nuoto float(53) not null,
        piume varchar(255) not null,
        primary key (id)
    );

    create table prodotti (
        biglietti integer unique,
        id integer generated by default as identity,
        prezzo_prodotto integer not null,
        nome_prodotto varchar(255) not null,
        primary key (id)
    );

    create table scimmie (
        coda_prensile boolean not null,
        id integer not null,
        tipo_dentatura varchar(30) not null,
        tipo_movimenti varchar(30) not null,
        primary key (id)
    );

    create table serpenti (
        id integer not null,
        lunghezza_cm integer not null,
        tempo_digestione_giorni integer not null,
        velenoso boolean not null,
        zanne boolean not null,
        primary key (id)
    );

    create table tartarughe (
        id integer not null,
        letargo boolean not null,
        ovipara boolean not null,
        tipo varchar(255) not null,
        primary key (id)
    );

    create table turni (
        fine_turno time(0) not null,
        id integer generated by default as identity,
        inizio_turno time(0) not null,
        primary key (id)
    );

    create table utenti (
        clienti integer unique,
        dipendenti integer unique,
        id integer generated by default as identity,
        role smallint not null check ((role between 0 and 3)),
        email varchar(255) not null,
        pwd varchar(255) not null,
        user_name varchar(255) not null,
        primary key (id)
    );

    alter table if exists animali 
       add constraint FKh4772d29qhfyksnsc9ib9dise 
       foreign key (area) 
       references area;

    alter table if exists animali 
       add constraint FKsyr7mxgy0xkl1c4ufoidgcj8o 
       foreign key (mangime) 
       references mangime;

    alter table if exists area 
       add constraint FK58cx5f7827h15xey6pta359vm 
       foreign key (turni) 
       references turni;

    alter table if exists area 
       add constraint FKqyufmy0nn4gryp7ybjr1a9qp7 
       foreign key (area) 
       references turni;

    alter table if exists biglietti 
       add constraint FKa9qpqe8ph6vi4s58ld1v8xy49 
       foreign key (eventi) 
       references eventi;

    alter table if exists biglietti 
       add constraint FK1bmp98ht8pfncacgxhy37umth 
       foreign key (prodotti) 
       references prodotti;

    alter table if exists clienti 
       add constraint FKt9b2l6259oklgl24liwqr269o 
       foreign key (utenti) 
       references utenti;

    alter table if exists delfini 
       add constraint FKaikh4o556oshv8bimioios4vw 
       foreign key (id) 
       references animali;

    alter table if exists dipendenti 
       add constraint FKf92w72v7612ypcdf2oon93ggy 
       foreign key (area) 
       references area;

    alter table if exists dipendenti 
       add constraint FKiw1ncoi6fndn5apdn3ygnksq9 
       foreign key (utenti) 
       references utenti;

    alter table if exists giornata_zoo 
       add constraint FK2hc1cgyewdkxx4ww4ll3aj176 
       foreign key (eventi) 
       references eventi;

    alter table if exists giornata_zoo 
       add constraint FKjomjxpcfflmckds7alfucrx58 
       foreign key (giornate) 
       references eventi;

    alter table if exists lemuri 
       add constraint FKql8qdh6ba9uka6ms1uq9uwgp6 
       foreign key (id) 
       references animali;

    alter table if exists leoni 
       add constraint FKc71c0urjkly4y272ptk8q9f82 
       foreign key (id) 
       references animali;

    alter table if exists mangime 
       add constraint FKi6eamu3q1o78675ksaa1pwrp3 
       foreign key (animali) 
       references animali;

    alter table if exists movimenti_mangime 
       add constraint FKoyn1cvbkee7ly31owr4gkyoj7 
       foreign key (dipendenti) 
       references dipendenti;

    alter table if exists movimenti_mangime 
       add constraint FK3cees6y41clh5wd01kuym8vkp 
       foreign key (movimenti_mangime) 
       references dipendenti;

    alter table if exists oggetti_ordine 
       add constraint FKr51g644e9d6no9q59hhrqkf26 
       foreign key (ordini) 
       references ordine;

    alter table if exists oggetti_ordine 
       add constraint FKmfa4q2yt6eb8fl8bddfoj6cp5 
       foreign key (prodotti) 
       references prodotti;

    alter table if exists oggetti_ordine 
       add constraint FK36gjgowybkg1iwr87vwt6co96 
       foreign key (oggetti_ordini) 
       references prodotti;

    alter table if exists oggetti_ordine 
       add constraint FKl463u7rwv54ynoft8nh0hf872 
       foreign key (oggetti_ordine) 
       references ordine;

    alter table if exists ordine 
       add constraint FK9aqtlofxcuoakkgdmonvalmje 
       foreign key (ordine) 
       references clienti;

    alter table if exists pesci 
       add constraint FKdw5iqq1aj9wq7qp2ajn143psc 
       foreign key (id) 
       references animali;

    alter table if exists pinguini 
       add constraint FKdxadp8w25mdifsepy1bjvbiwl 
       foreign key (id) 
       references animali;

    alter table if exists prodotti 
       add constraint FKn52bwip863qpm6uejbrg7w470 
       foreign key (biglietti) 
       references biglietti;

    alter table if exists scimmie 
       add constraint FKa4sm58jo81j4doq8nn9ae9d8b 
       foreign key (id) 
       references animali;

    alter table if exists serpenti 
       add constraint FKs0xkhgmahthc0apv90pnd1xk3 
       foreign key (id) 
       references animali;

    alter table if exists tartarughe 
       add constraint FK6wciko8y5ghilsaopulb9v5k 
       foreign key (id) 
       references animali;

    alter table if exists utenti 
       add constraint FKph5t4nnxcvxmjtmko0plgkjid 
       foreign key (clienti) 
       references clienti;

    alter table if exists utenti 
       add constraint FKdo1vk3w751hiuoqxdl4r2mmy9 
       foreign key (dipendenti) 
       references dipendenti;
